// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collaborationrequest.proto

package com.neevtech.gpb;

public final class CollaborationRequestProtos {
  private CollaborationRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CollaborationRequestProtoObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string serviceRequestId = 1;
    /**
     * <code>required string serviceRequestId = 1;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    boolean hasServiceRequestId();
    /**
     * <code>required string serviceRequestId = 1;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    java.lang.String getServiceRequestId();
    /**
     * <code>required string serviceRequestId = 1;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    com.google.protobuf.ByteString
        getServiceRequestIdBytes();

    // optional string indicator = 2;
    /**
     * <code>optional string indicator = 2;</code>
     */
    boolean hasIndicator();
    /**
     * <code>optional string indicator = 2;</code>
     */
    java.lang.String getIndicator();
    /**
     * <code>optional string indicator = 2;</code>
     */
    com.google.protobuf.ByteString
        getIndicatorBytes();

    // optional string requester = 3;
    /**
     * <code>optional string requester = 3;</code>
     */
    boolean hasRequester();
    /**
     * <code>optional string requester = 3;</code>
     */
    java.lang.String getRequester();
    /**
     * <code>optional string requester = 3;</code>
     */
    com.google.protobuf.ByteString
        getRequesterBytes();

    // optional string collaborationType = 4;
    /**
     * <code>optional string collaborationType = 4;</code>
     */
    boolean hasCollaborationType();
    /**
     * <code>optional string collaborationType = 4;</code>
     */
    java.lang.String getCollaborationType();
    /**
     * <code>optional string collaborationType = 4;</code>
     */
    com.google.protobuf.ByteString
        getCollaborationTypeBytes();

    // optional string collTechId = 5;
    /**
     * <code>optional string collTechId = 5;</code>
     */
    boolean hasCollTechId();
    /**
     * <code>optional string collTechId = 5;</code>
     */
    java.lang.String getCollTechId();
    /**
     * <code>optional string collTechId = 5;</code>
     */
    com.google.protobuf.ByteString
        getCollTechIdBytes();

    // optional string collSubTechId = 6;
    /**
     * <code>optional string collSubTechId = 6;</code>
     */
    boolean hasCollSubTechId();
    /**
     * <code>optional string collSubTechId = 6;</code>
     */
    java.lang.String getCollSubTechId();
    /**
     * <code>optional string collSubTechId = 6;</code>
     */
    com.google.protobuf.ByteString
        getCollSubTechIdBytes();

    // optional string collProbCode = 7;
    /**
     * <code>optional string collProbCode = 7;</code>
     */
    boolean hasCollProbCode();
    /**
     * <code>optional string collProbCode = 7;</code>
     */
    java.lang.String getCollProbCode();
    /**
     * <code>optional string collProbCode = 7;</code>
     */
    com.google.protobuf.ByteString
        getCollProbCodeBytes();

    // optional string collCreateDate = 8;
    /**
     * <code>optional string collCreateDate = 8;</code>
     */
    boolean hasCollCreateDate();
    /**
     * <code>optional string collCreateDate = 8;</code>
     */
    java.lang.String getCollCreateDate();
    /**
     * <code>optional string collCreateDate = 8;</code>
     */
    com.google.protobuf.ByteString
        getCollCreateDateBytes();

    // optional string initiator = 9;
    /**
     * <code>optional string initiator = 9;</code>
     */
    boolean hasInitiator();
    /**
     * <code>optional string initiator = 9;</code>
     */
    java.lang.String getInitiator();
    /**
     * <code>optional string initiator = 9;</code>
     */
    com.google.protobuf.ByteString
        getInitiatorBytes();

    // optional string collExtId = 10;
    /**
     * <code>optional string collExtId = 10;</code>
     */
    boolean hasCollExtId();
    /**
     * <code>optional string collExtId = 10;</code>
     */
    java.lang.String getCollExtId();
    /**
     * <code>optional string collExtId = 10;</code>
     */
    com.google.protobuf.ByteString
        getCollExtIdBytes();

    // optional string collabOwner = 11;
    /**
     * <code>optional string collabOwner = 11;</code>
     */
    boolean hasCollabOwner();
    /**
     * <code>optional string collabOwner = 11;</code>
     */
    java.lang.String getCollabOwner();
    /**
     * <code>optional string collabOwner = 11;</code>
     */
    com.google.protobuf.ByteString
        getCollabOwnerBytes();

    // optional int32 severity = 12;
    /**
     * <code>optional int32 severity = 12;</code>
     */
    boolean hasSeverity();
    /**
     * <code>optional int32 severity = 12;</code>
     */
    int getSeverity();

    // optional string breTransactionId = 13;
    /**
     * <code>optional string breTransactionId = 13;</code>
     */
    boolean hasBreTransactionId();
    /**
     * <code>optional string breTransactionId = 13;</code>
     */
    java.lang.String getBreTransactionId();
    /**
     * <code>optional string breTransactionId = 13;</code>
     */
    com.google.protobuf.ByteString
        getBreTransactionIdBytes();

    // optional string skillId = 14;
    /**
     * <code>optional string skillId = 14;</code>
     */
    boolean hasSkillId();
    /**
     * <code>optional string skillId = 14;</code>
     */
    java.lang.String getSkillId();
    /**
     * <code>optional string skillId = 14;</code>
     */
    com.google.protobuf.ByteString
        getSkillIdBytes();

    // optional string collaborationSubType = 15;
    /**
     * <code>optional string collaborationSubType = 15;</code>
     */
    boolean hasCollaborationSubType();
    /**
     * <code>optional string collaborationSubType = 15;</code>
     */
    java.lang.String getCollaborationSubType();
    /**
     * <code>optional string collaborationSubType = 15;</code>
     */
    com.google.protobuf.ByteString
        getCollaborationSubTypeBytes();
  }
  /**
   * Protobuf type {@code CollaborationRequestProtoObject}
   */
  public static final class CollaborationRequestProtoObject extends
      com.google.protobuf.GeneratedMessage
      implements CollaborationRequestProtoObjectOrBuilder {
    // Use CollaborationRequestProtoObject.newBuilder() to construct.
    private CollaborationRequestProtoObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CollaborationRequestProtoObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CollaborationRequestProtoObject defaultInstance;
    public static CollaborationRequestProtoObject getDefaultInstance() {
      return defaultInstance;
    }

    public CollaborationRequestProtoObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CollaborationRequestProtoObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceRequestId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              indicator_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requester_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              collaborationType_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              collTechId_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              collSubTechId_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              collProbCode_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              collCreateDate_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              initiator_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              collExtId_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              collabOwner_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              severity_ = input.readInt32();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              breTransactionId_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              skillId_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              collaborationSubType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neevtech.gpb.CollaborationRequestProtos.internal_static_CollaborationRequestProtoObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neevtech.gpb.CollaborationRequestProtos.internal_static_CollaborationRequestProtoObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject.class, com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject.Builder.class);
    }

    public static com.google.protobuf.Parser<CollaborationRequestProtoObject> PARSER =
        new com.google.protobuf.AbstractParser<CollaborationRequestProtoObject>() {
      public CollaborationRequestProtoObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CollaborationRequestProtoObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CollaborationRequestProtoObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string serviceRequestId = 1;
    public static final int SERVICEREQUESTID_FIELD_NUMBER = 1;
    private java.lang.Object serviceRequestId_;
    /**
     * <code>required string serviceRequestId = 1;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    public boolean hasServiceRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serviceRequestId = 1;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    public java.lang.String getServiceRequestId() {
      java.lang.Object ref = serviceRequestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceRequestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serviceRequestId = 1;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServiceRequestIdBytes() {
      java.lang.Object ref = serviceRequestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceRequestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string indicator = 2;
    public static final int INDICATOR_FIELD_NUMBER = 2;
    private java.lang.Object indicator_;
    /**
     * <code>optional string indicator = 2;</code>
     */
    public boolean hasIndicator() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string indicator = 2;</code>
     */
    public java.lang.String getIndicator() {
      java.lang.Object ref = indicator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          indicator_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string indicator = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIndicatorBytes() {
      java.lang.Object ref = indicator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indicator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string requester = 3;
    public static final int REQUESTER_FIELD_NUMBER = 3;
    private java.lang.Object requester_;
    /**
     * <code>optional string requester = 3;</code>
     */
    public boolean hasRequester() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string requester = 3;</code>
     */
    public java.lang.String getRequester() {
      java.lang.Object ref = requester_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requester_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requester = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequesterBytes() {
      java.lang.Object ref = requester_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requester_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collaborationType = 4;
    public static final int COLLABORATIONTYPE_FIELD_NUMBER = 4;
    private java.lang.Object collaborationType_;
    /**
     * <code>optional string collaborationType = 4;</code>
     */
    public boolean hasCollaborationType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string collaborationType = 4;</code>
     */
    public java.lang.String getCollaborationType() {
      java.lang.Object ref = collaborationType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collaborationType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collaborationType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCollaborationTypeBytes() {
      java.lang.Object ref = collaborationType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collaborationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collTechId = 5;
    public static final int COLLTECHID_FIELD_NUMBER = 5;
    private java.lang.Object collTechId_;
    /**
     * <code>optional string collTechId = 5;</code>
     */
    public boolean hasCollTechId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string collTechId = 5;</code>
     */
    public java.lang.String getCollTechId() {
      java.lang.Object ref = collTechId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collTechId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collTechId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCollTechIdBytes() {
      java.lang.Object ref = collTechId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collTechId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collSubTechId = 6;
    public static final int COLLSUBTECHID_FIELD_NUMBER = 6;
    private java.lang.Object collSubTechId_;
    /**
     * <code>optional string collSubTechId = 6;</code>
     */
    public boolean hasCollSubTechId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string collSubTechId = 6;</code>
     */
    public java.lang.String getCollSubTechId() {
      java.lang.Object ref = collSubTechId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collSubTechId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collSubTechId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCollSubTechIdBytes() {
      java.lang.Object ref = collSubTechId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collSubTechId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collProbCode = 7;
    public static final int COLLPROBCODE_FIELD_NUMBER = 7;
    private java.lang.Object collProbCode_;
    /**
     * <code>optional string collProbCode = 7;</code>
     */
    public boolean hasCollProbCode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string collProbCode = 7;</code>
     */
    public java.lang.String getCollProbCode() {
      java.lang.Object ref = collProbCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collProbCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collProbCode = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCollProbCodeBytes() {
      java.lang.Object ref = collProbCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collProbCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collCreateDate = 8;
    public static final int COLLCREATEDATE_FIELD_NUMBER = 8;
    private java.lang.Object collCreateDate_;
    /**
     * <code>optional string collCreateDate = 8;</code>
     */
    public boolean hasCollCreateDate() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string collCreateDate = 8;</code>
     */
    public java.lang.String getCollCreateDate() {
      java.lang.Object ref = collCreateDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collCreateDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collCreateDate = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCollCreateDateBytes() {
      java.lang.Object ref = collCreateDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collCreateDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string initiator = 9;
    public static final int INITIATOR_FIELD_NUMBER = 9;
    private java.lang.Object initiator_;
    /**
     * <code>optional string initiator = 9;</code>
     */
    public boolean hasInitiator() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string initiator = 9;</code>
     */
    public java.lang.String getInitiator() {
      java.lang.Object ref = initiator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          initiator_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string initiator = 9;</code>
     */
    public com.google.protobuf.ByteString
        getInitiatorBytes() {
      java.lang.Object ref = initiator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initiator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collExtId = 10;
    public static final int COLLEXTID_FIELD_NUMBER = 10;
    private java.lang.Object collExtId_;
    /**
     * <code>optional string collExtId = 10;</code>
     */
    public boolean hasCollExtId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string collExtId = 10;</code>
     */
    public java.lang.String getCollExtId() {
      java.lang.Object ref = collExtId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collExtId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collExtId = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCollExtIdBytes() {
      java.lang.Object ref = collExtId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collExtId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collabOwner = 11;
    public static final int COLLABOWNER_FIELD_NUMBER = 11;
    private java.lang.Object collabOwner_;
    /**
     * <code>optional string collabOwner = 11;</code>
     */
    public boolean hasCollabOwner() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string collabOwner = 11;</code>
     */
    public java.lang.String getCollabOwner() {
      java.lang.Object ref = collabOwner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collabOwner_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collabOwner = 11;</code>
     */
    public com.google.protobuf.ByteString
        getCollabOwnerBytes() {
      java.lang.Object ref = collabOwner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collabOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 severity = 12;
    public static final int SEVERITY_FIELD_NUMBER = 12;
    private int severity_;
    /**
     * <code>optional int32 severity = 12;</code>
     */
    public boolean hasSeverity() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 severity = 12;</code>
     */
    public int getSeverity() {
      return severity_;
    }

    // optional string breTransactionId = 13;
    public static final int BRETRANSACTIONID_FIELD_NUMBER = 13;
    private java.lang.Object breTransactionId_;
    /**
     * <code>optional string breTransactionId = 13;</code>
     */
    public boolean hasBreTransactionId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string breTransactionId = 13;</code>
     */
    public java.lang.String getBreTransactionId() {
      java.lang.Object ref = breTransactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          breTransactionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string breTransactionId = 13;</code>
     */
    public com.google.protobuf.ByteString
        getBreTransactionIdBytes() {
      java.lang.Object ref = breTransactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        breTransactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string skillId = 14;
    public static final int SKILLID_FIELD_NUMBER = 14;
    private java.lang.Object skillId_;
    /**
     * <code>optional string skillId = 14;</code>
     */
    public boolean hasSkillId() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string skillId = 14;</code>
     */
    public java.lang.String getSkillId() {
      java.lang.Object ref = skillId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          skillId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string skillId = 14;</code>
     */
    public com.google.protobuf.ByteString
        getSkillIdBytes() {
      java.lang.Object ref = skillId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collaborationSubType = 15;
    public static final int COLLABORATIONSUBTYPE_FIELD_NUMBER = 15;
    private java.lang.Object collaborationSubType_;
    /**
     * <code>optional string collaborationSubType = 15;</code>
     */
    public boolean hasCollaborationSubType() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string collaborationSubType = 15;</code>
     */
    public java.lang.String getCollaborationSubType() {
      java.lang.Object ref = collaborationSubType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collaborationSubType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collaborationSubType = 15;</code>
     */
    public com.google.protobuf.ByteString
        getCollaborationSubTypeBytes() {
      java.lang.Object ref = collaborationSubType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collaborationSubType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serviceRequestId_ = "";
      indicator_ = "";
      requester_ = "";
      collaborationType_ = "";
      collTechId_ = "";
      collSubTechId_ = "";
      collProbCode_ = "";
      collCreateDate_ = "";
      initiator_ = "";
      collExtId_ = "";
      collabOwner_ = "";
      severity_ = 0;
      breTransactionId_ = "";
      skillId_ = "";
      collaborationSubType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServiceRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIndicatorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRequesterBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCollaborationTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getCollTechIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCollSubTechIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getCollProbCodeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getCollCreateDateBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getInitiatorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getCollExtIdBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getCollabOwnerBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, severity_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getBreTransactionIdBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getSkillIdBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getCollaborationSubTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIndicatorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRequesterBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCollaborationTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCollTechIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCollSubTechIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getCollProbCodeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getCollCreateDateBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getInitiatorBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getCollExtIdBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getCollabOwnerBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, severity_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getBreTransactionIdBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getSkillIdBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getCollaborationSubTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CollaborationRequestProtoObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.neevtech.gpb.CollaborationRequestProtos.internal_static_CollaborationRequestProtoObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.neevtech.gpb.CollaborationRequestProtos.internal_static_CollaborationRequestProtoObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject.class, com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject.Builder.class);
      }

      // Construct using com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceRequestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        indicator_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requester_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        collaborationType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        collTechId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        collSubTechId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        collProbCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        collCreateDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        initiator_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        collExtId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        collabOwner_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        severity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        breTransactionId_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        skillId_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        collaborationSubType_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.neevtech.gpb.CollaborationRequestProtos.internal_static_CollaborationRequestProtoObject_descriptor;
      }

      public com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject getDefaultInstanceForType() {
        return com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject.getDefaultInstance();
      }

      public com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject build() {
        com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject buildPartial() {
        com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject result = new com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceRequestId_ = serviceRequestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.indicator_ = indicator_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requester_ = requester_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.collaborationType_ = collaborationType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.collTechId_ = collTechId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.collSubTechId_ = collSubTechId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.collProbCode_ = collProbCode_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.collCreateDate_ = collCreateDate_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.initiator_ = initiator_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.collExtId_ = collExtId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.collabOwner_ = collabOwner_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.severity_ = severity_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.breTransactionId_ = breTransactionId_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.skillId_ = skillId_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.collaborationSubType_ = collaborationSubType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject) {
          return mergeFrom((com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject other) {
        if (other == com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject.getDefaultInstance()) return this;
        if (other.hasServiceRequestId()) {
          bitField0_ |= 0x00000001;
          serviceRequestId_ = other.serviceRequestId_;
          onChanged();
        }
        if (other.hasIndicator()) {
          bitField0_ |= 0x00000002;
          indicator_ = other.indicator_;
          onChanged();
        }
        if (other.hasRequester()) {
          bitField0_ |= 0x00000004;
          requester_ = other.requester_;
          onChanged();
        }
        if (other.hasCollaborationType()) {
          bitField0_ |= 0x00000008;
          collaborationType_ = other.collaborationType_;
          onChanged();
        }
        if (other.hasCollTechId()) {
          bitField0_ |= 0x00000010;
          collTechId_ = other.collTechId_;
          onChanged();
        }
        if (other.hasCollSubTechId()) {
          bitField0_ |= 0x00000020;
          collSubTechId_ = other.collSubTechId_;
          onChanged();
        }
        if (other.hasCollProbCode()) {
          bitField0_ |= 0x00000040;
          collProbCode_ = other.collProbCode_;
          onChanged();
        }
        if (other.hasCollCreateDate()) {
          bitField0_ |= 0x00000080;
          collCreateDate_ = other.collCreateDate_;
          onChanged();
        }
        if (other.hasInitiator()) {
          bitField0_ |= 0x00000100;
          initiator_ = other.initiator_;
          onChanged();
        }
        if (other.hasCollExtId()) {
          bitField0_ |= 0x00000200;
          collExtId_ = other.collExtId_;
          onChanged();
        }
        if (other.hasCollabOwner()) {
          bitField0_ |= 0x00000400;
          collabOwner_ = other.collabOwner_;
          onChanged();
        }
        if (other.hasSeverity()) {
          setSeverity(other.getSeverity());
        }
        if (other.hasBreTransactionId()) {
          bitField0_ |= 0x00001000;
          breTransactionId_ = other.breTransactionId_;
          onChanged();
        }
        if (other.hasSkillId()) {
          bitField0_ |= 0x00002000;
          skillId_ = other.skillId_;
          onChanged();
        }
        if (other.hasCollaborationSubType()) {
          bitField0_ |= 0x00004000;
          collaborationSubType_ = other.collaborationSubType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceRequestId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.neevtech.gpb.CollaborationRequestProtos.CollaborationRequestProtoObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string serviceRequestId = 1;
      private java.lang.Object serviceRequestId_ = "";
      /**
       * <code>required string serviceRequestId = 1;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public boolean hasServiceRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serviceRequestId = 1;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public java.lang.String getServiceRequestId() {
        java.lang.Object ref = serviceRequestId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceRequestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serviceRequestId = 1;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServiceRequestIdBytes() {
        java.lang.Object ref = serviceRequestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceRequestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serviceRequestId = 1;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public Builder setServiceRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceRequestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceRequestId = 1;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public Builder clearServiceRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceRequestId_ = getDefaultInstance().getServiceRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceRequestId = 1;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public Builder setServiceRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceRequestId_ = value;
        onChanged();
        return this;
      }

      // optional string indicator = 2;
      private java.lang.Object indicator_ = "";
      /**
       * <code>optional string indicator = 2;</code>
       */
      public boolean hasIndicator() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string indicator = 2;</code>
       */
      public java.lang.String getIndicator() {
        java.lang.Object ref = indicator_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          indicator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string indicator = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIndicatorBytes() {
        java.lang.Object ref = indicator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          indicator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string indicator = 2;</code>
       */
      public Builder setIndicator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        indicator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string indicator = 2;</code>
       */
      public Builder clearIndicator() {
        bitField0_ = (bitField0_ & ~0x00000002);
        indicator_ = getDefaultInstance().getIndicator();
        onChanged();
        return this;
      }
      /**
       * <code>optional string indicator = 2;</code>
       */
      public Builder setIndicatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        indicator_ = value;
        onChanged();
        return this;
      }

      // optional string requester = 3;
      private java.lang.Object requester_ = "";
      /**
       * <code>optional string requester = 3;</code>
       */
      public boolean hasRequester() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string requester = 3;</code>
       */
      public java.lang.String getRequester() {
        java.lang.Object ref = requester_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requester_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requester = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRequesterBytes() {
        java.lang.Object ref = requester_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requester_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requester = 3;</code>
       */
      public Builder setRequester(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requester_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requester = 3;</code>
       */
      public Builder clearRequester() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requester_ = getDefaultInstance().getRequester();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requester = 3;</code>
       */
      public Builder setRequesterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requester_ = value;
        onChanged();
        return this;
      }

      // optional string collaborationType = 4;
      private java.lang.Object collaborationType_ = "";
      /**
       * <code>optional string collaborationType = 4;</code>
       */
      public boolean hasCollaborationType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string collaborationType = 4;</code>
       */
      public java.lang.String getCollaborationType() {
        java.lang.Object ref = collaborationType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collaborationType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collaborationType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCollaborationTypeBytes() {
        java.lang.Object ref = collaborationType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collaborationType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collaborationType = 4;</code>
       */
      public Builder setCollaborationType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        collaborationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collaborationType = 4;</code>
       */
      public Builder clearCollaborationType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        collaborationType_ = getDefaultInstance().getCollaborationType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collaborationType = 4;</code>
       */
      public Builder setCollaborationTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        collaborationType_ = value;
        onChanged();
        return this;
      }

      // optional string collTechId = 5;
      private java.lang.Object collTechId_ = "";
      /**
       * <code>optional string collTechId = 5;</code>
       */
      public boolean hasCollTechId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string collTechId = 5;</code>
       */
      public java.lang.String getCollTechId() {
        java.lang.Object ref = collTechId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collTechId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collTechId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCollTechIdBytes() {
        java.lang.Object ref = collTechId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collTechId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collTechId = 5;</code>
       */
      public Builder setCollTechId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        collTechId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collTechId = 5;</code>
       */
      public Builder clearCollTechId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        collTechId_ = getDefaultInstance().getCollTechId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collTechId = 5;</code>
       */
      public Builder setCollTechIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        collTechId_ = value;
        onChanged();
        return this;
      }

      // optional string collSubTechId = 6;
      private java.lang.Object collSubTechId_ = "";
      /**
       * <code>optional string collSubTechId = 6;</code>
       */
      public boolean hasCollSubTechId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string collSubTechId = 6;</code>
       */
      public java.lang.String getCollSubTechId() {
        java.lang.Object ref = collSubTechId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collSubTechId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collSubTechId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCollSubTechIdBytes() {
        java.lang.Object ref = collSubTechId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collSubTechId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collSubTechId = 6;</code>
       */
      public Builder setCollSubTechId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        collSubTechId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collSubTechId = 6;</code>
       */
      public Builder clearCollSubTechId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        collSubTechId_ = getDefaultInstance().getCollSubTechId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collSubTechId = 6;</code>
       */
      public Builder setCollSubTechIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        collSubTechId_ = value;
        onChanged();
        return this;
      }

      // optional string collProbCode = 7;
      private java.lang.Object collProbCode_ = "";
      /**
       * <code>optional string collProbCode = 7;</code>
       */
      public boolean hasCollProbCode() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string collProbCode = 7;</code>
       */
      public java.lang.String getCollProbCode() {
        java.lang.Object ref = collProbCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collProbCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collProbCode = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCollProbCodeBytes() {
        java.lang.Object ref = collProbCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collProbCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collProbCode = 7;</code>
       */
      public Builder setCollProbCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        collProbCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collProbCode = 7;</code>
       */
      public Builder clearCollProbCode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        collProbCode_ = getDefaultInstance().getCollProbCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collProbCode = 7;</code>
       */
      public Builder setCollProbCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        collProbCode_ = value;
        onChanged();
        return this;
      }

      // optional string collCreateDate = 8;
      private java.lang.Object collCreateDate_ = "";
      /**
       * <code>optional string collCreateDate = 8;</code>
       */
      public boolean hasCollCreateDate() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string collCreateDate = 8;</code>
       */
      public java.lang.String getCollCreateDate() {
        java.lang.Object ref = collCreateDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collCreateDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collCreateDate = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCollCreateDateBytes() {
        java.lang.Object ref = collCreateDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collCreateDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collCreateDate = 8;</code>
       */
      public Builder setCollCreateDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        collCreateDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collCreateDate = 8;</code>
       */
      public Builder clearCollCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        collCreateDate_ = getDefaultInstance().getCollCreateDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collCreateDate = 8;</code>
       */
      public Builder setCollCreateDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        collCreateDate_ = value;
        onChanged();
        return this;
      }

      // optional string initiator = 9;
      private java.lang.Object initiator_ = "";
      /**
       * <code>optional string initiator = 9;</code>
       */
      public boolean hasInitiator() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string initiator = 9;</code>
       */
      public java.lang.String getInitiator() {
        java.lang.Object ref = initiator_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          initiator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string initiator = 9;</code>
       */
      public com.google.protobuf.ByteString
          getInitiatorBytes() {
        java.lang.Object ref = initiator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          initiator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string initiator = 9;</code>
       */
      public Builder setInitiator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        initiator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string initiator = 9;</code>
       */
      public Builder clearInitiator() {
        bitField0_ = (bitField0_ & ~0x00000100);
        initiator_ = getDefaultInstance().getInitiator();
        onChanged();
        return this;
      }
      /**
       * <code>optional string initiator = 9;</code>
       */
      public Builder setInitiatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        initiator_ = value;
        onChanged();
        return this;
      }

      // optional string collExtId = 10;
      private java.lang.Object collExtId_ = "";
      /**
       * <code>optional string collExtId = 10;</code>
       */
      public boolean hasCollExtId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string collExtId = 10;</code>
       */
      public java.lang.String getCollExtId() {
        java.lang.Object ref = collExtId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collExtId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collExtId = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCollExtIdBytes() {
        java.lang.Object ref = collExtId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collExtId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collExtId = 10;</code>
       */
      public Builder setCollExtId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        collExtId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collExtId = 10;</code>
       */
      public Builder clearCollExtId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        collExtId_ = getDefaultInstance().getCollExtId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collExtId = 10;</code>
       */
      public Builder setCollExtIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        collExtId_ = value;
        onChanged();
        return this;
      }

      // optional string collabOwner = 11;
      private java.lang.Object collabOwner_ = "";
      /**
       * <code>optional string collabOwner = 11;</code>
       */
      public boolean hasCollabOwner() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string collabOwner = 11;</code>
       */
      public java.lang.String getCollabOwner() {
        java.lang.Object ref = collabOwner_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collabOwner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collabOwner = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCollabOwnerBytes() {
        java.lang.Object ref = collabOwner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collabOwner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collabOwner = 11;</code>
       */
      public Builder setCollabOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        collabOwner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collabOwner = 11;</code>
       */
      public Builder clearCollabOwner() {
        bitField0_ = (bitField0_ & ~0x00000400);
        collabOwner_ = getDefaultInstance().getCollabOwner();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collabOwner = 11;</code>
       */
      public Builder setCollabOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        collabOwner_ = value;
        onChanged();
        return this;
      }

      // optional int32 severity = 12;
      private int severity_ ;
      /**
       * <code>optional int32 severity = 12;</code>
       */
      public boolean hasSeverity() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 severity = 12;</code>
       */
      public int getSeverity() {
        return severity_;
      }
      /**
       * <code>optional int32 severity = 12;</code>
       */
      public Builder setSeverity(int value) {
        bitField0_ |= 0x00000800;
        severity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 severity = 12;</code>
       */
      public Builder clearSeverity() {
        bitField0_ = (bitField0_ & ~0x00000800);
        severity_ = 0;
        onChanged();
        return this;
      }

      // optional string breTransactionId = 13;
      private java.lang.Object breTransactionId_ = "";
      /**
       * <code>optional string breTransactionId = 13;</code>
       */
      public boolean hasBreTransactionId() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string breTransactionId = 13;</code>
       */
      public java.lang.String getBreTransactionId() {
        java.lang.Object ref = breTransactionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          breTransactionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string breTransactionId = 13;</code>
       */
      public com.google.protobuf.ByteString
          getBreTransactionIdBytes() {
        java.lang.Object ref = breTransactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          breTransactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string breTransactionId = 13;</code>
       */
      public Builder setBreTransactionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        breTransactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string breTransactionId = 13;</code>
       */
      public Builder clearBreTransactionId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        breTransactionId_ = getDefaultInstance().getBreTransactionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string breTransactionId = 13;</code>
       */
      public Builder setBreTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        breTransactionId_ = value;
        onChanged();
        return this;
      }

      // optional string skillId = 14;
      private java.lang.Object skillId_ = "";
      /**
       * <code>optional string skillId = 14;</code>
       */
      public boolean hasSkillId() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string skillId = 14;</code>
       */
      public java.lang.String getSkillId() {
        java.lang.Object ref = skillId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          skillId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string skillId = 14;</code>
       */
      public com.google.protobuf.ByteString
          getSkillIdBytes() {
        java.lang.Object ref = skillId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string skillId = 14;</code>
       */
      public Builder setSkillId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        skillId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string skillId = 14;</code>
       */
      public Builder clearSkillId() {
        bitField0_ = (bitField0_ & ~0x00002000);
        skillId_ = getDefaultInstance().getSkillId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string skillId = 14;</code>
       */
      public Builder setSkillIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        skillId_ = value;
        onChanged();
        return this;
      }

      // optional string collaborationSubType = 15;
      private java.lang.Object collaborationSubType_ = "";
      /**
       * <code>optional string collaborationSubType = 15;</code>
       */
      public boolean hasCollaborationSubType() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional string collaborationSubType = 15;</code>
       */
      public java.lang.String getCollaborationSubType() {
        java.lang.Object ref = collaborationSubType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collaborationSubType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collaborationSubType = 15;</code>
       */
      public com.google.protobuf.ByteString
          getCollaborationSubTypeBytes() {
        java.lang.Object ref = collaborationSubType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collaborationSubType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collaborationSubType = 15;</code>
       */
      public Builder setCollaborationSubType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        collaborationSubType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collaborationSubType = 15;</code>
       */
      public Builder clearCollaborationSubType() {
        bitField0_ = (bitField0_ & ~0x00004000);
        collaborationSubType_ = getDefaultInstance().getCollaborationSubType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collaborationSubType = 15;</code>
       */
      public Builder setCollaborationSubTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        collaborationSubType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CollaborationRequestProtoObject)
    }

    static {
      defaultInstance = new CollaborationRequestProtoObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CollaborationRequestProtoObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CollaborationRequestProtoObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CollaborationRequestProtoObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032collaborationrequest.proto\"\353\002\n\037Collabo" +
      "rationRequestProtoObject\022\030\n\020serviceReque" +
      "stId\030\001 \002(\t\022\021\n\tindicator\030\002 \001(\t\022\021\n\trequest" +
      "er\030\003 \001(\t\022\031\n\021collaborationType\030\004 \001(\t\022\022\n\nc" +
      "ollTechId\030\005 \001(\t\022\025\n\rcollSubTechId\030\006 \001(\t\022\024" +
      "\n\014collProbCode\030\007 \001(\t\022\026\n\016collCreateDate\030\010" +
      " \001(\t\022\021\n\tinitiator\030\t \001(\t\022\021\n\tcollExtId\030\n \001" +
      "(\t\022\023\n\013collabOwner\030\013 \001(\t\022\020\n\010severity\030\014 \001(" +
      "\005\022\030\n\020breTransactionId\030\r \001(\t\022\017\n\007skillId\030\016" +
      " \001(\t\022\034\n\024collaborationSubType\030\017 \001(\tB.\n\020co",
      "m.neevtech.gpbB\032CollaborationRequestProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CollaborationRequestProtoObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CollaborationRequestProtoObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CollaborationRequestProtoObject_descriptor,
              new java.lang.String[] { "ServiceRequestId", "Indicator", "Requester", "CollaborationType", "CollTechId", "CollSubTechId", "CollProbCode", "CollCreateDate", "Initiator", "CollExtId", "CollabOwner", "Severity", "BreTransactionId", "SkillId", "CollaborationSubType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
