// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.neevtech.gpb;

public final class CustomerProtos {
  private CustomerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomerProtoObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string city = 1;
    /**
     * <code>optional string city = 1;</code>
     */
    boolean hasCity();
    /**
     * <code>optional string city = 1;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 1;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    // optional int32 classificationPoints = 2;
    /**
     * <code>optional int32 classificationPoints = 2;</code>
     */
    boolean hasClassificationPoints();
    /**
     * <code>optional int32 classificationPoints = 2;</code>
     */
    int getClassificationPoints();

    // optional string country = 3;
    /**
     * <code>optional string country = 3;</code>
     */
    boolean hasCountry();
    /**
     * <code>optional string country = 3;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>optional string country = 3;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    // required string customerId = 4;
    /**
     * <code>required string customerId = 4;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    boolean hasCustomerId();
    /**
     * <code>required string customerId = 4;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    java.lang.String getCustomerId();
    /**
     * <code>required string customerId = 4;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    // optional string customerName = 5;
    /**
     * <code>optional string customerName = 5;</code>
     */
    boolean hasCustomerName();
    /**
     * <code>optional string customerName = 5;</code>
     */
    java.lang.String getCustomerName();
    /**
     * <code>optional string customerName = 5;</code>
     */
    com.google.protobuf.ByteString
        getCustomerNameBytes();

    // optional string customerType = 6;
    /**
     * <code>optional string customerType = 6;</code>
     */
    boolean hasCustomerType();
    /**
     * <code>optional string customerType = 6;</code>
     */
    java.lang.String getCustomerType();
    /**
     * <code>optional string customerType = 6;</code>
     */
    com.google.protobuf.ByteString
        getCustomerTypeBytes();

    // optional string territory = 7;
    /**
     * <code>optional string territory = 7;</code>
     */
    boolean hasTerritory();
    /**
     * <code>optional string territory = 7;</code>
     */
    java.lang.String getTerritory();
    /**
     * <code>optional string territory = 7;</code>
     */
    com.google.protobuf.ByteString
        getTerritoryBytes();

    // optional int32 valuePoint = 8;
    /**
     * <code>optional int32 valuePoint = 8;</code>
     */
    boolean hasValuePoint();
    /**
     * <code>optional int32 valuePoint = 8;</code>
     */
    int getValuePoint();

    // optional string classLabel = 9 [default = "NONE"];
    /**
     * <code>optional string classLabel = 9 [default = "NONE"];</code>
     */
    boolean hasClassLabel();
    /**
     * <code>optional string classLabel = 9 [default = "NONE"];</code>
     */
    java.lang.String getClassLabel();
    /**
     * <code>optional string classLabel = 9 [default = "NONE"];</code>
     */
    com.google.protobuf.ByteString
        getClassLabelBytes();

    // optional bool cisco30 = 10;
    /**
     * <code>optional bool cisco30 = 10;</code>
     */
    boolean hasCisco30();
    /**
     * <code>optional bool cisco30 = 10;</code>
     */
    boolean getCisco30();

    // optional bool relationship = 11;
    /**
     * <code>optional bool relationship = 11;</code>
     */
    boolean hasRelationship();
    /**
     * <code>optional bool relationship = 11;</code>
     */
    boolean getRelationship();

    // optional bool differentiated = 12;
    /**
     * <code>optional bool differentiated = 12;</code>
     */
    boolean hasDifferentiated();
    /**
     * <code>optional bool differentiated = 12;</code>
     */
    boolean getDifferentiated();

    // optional int32 contractValue = 13;
    /**
     * <code>optional int32 contractValue = 13;</code>
     */
    boolean hasContractValue();
    /**
     * <code>optional int32 contractValue = 13;</code>
     */
    int getContractValue();

    // optional int32 loyaltyDuration = 14;
    /**
     * <code>optional int32 loyaltyDuration = 14;</code>
     */
    boolean hasLoyaltyDuration();
    /**
     * <code>optional int32 loyaltyDuration = 14;</code>
     */
    int getLoyaltyDuration();

    // optional bool onCap = 15;
    /**
     * <code>optional bool onCap = 15;</code>
     */
    boolean hasOnCap();
    /**
     * <code>optional bool onCap = 15;</code>
     */
    boolean getOnCap();

    // repeated string valueRulesFired = 16;
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    java.util.List<java.lang.String>
    getValueRulesFiredList();
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    int getValueRulesFiredCount();
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    java.lang.String getValueRulesFired(int index);
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    com.google.protobuf.ByteString
        getValueRulesFiredBytes(int index);

    // repeated int32 firedSet = 17;
    /**
     * <code>repeated int32 firedSet = 17;</code>
     */
    java.util.List<java.lang.Integer> getFiredSetList();
    /**
     * <code>repeated int32 firedSet = 17;</code>
     */
    int getFiredSetCount();
    /**
     * <code>repeated int32 firedSet = 17;</code>
     */
    int getFiredSet(int index);
  }
  /**
   * Protobuf type {@code CustomerProtoObject}
   */
  public static final class CustomerProtoObject extends
      com.google.protobuf.GeneratedMessage
      implements CustomerProtoObjectOrBuilder {
    // Use CustomerProtoObject.newBuilder() to construct.
    private CustomerProtoObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomerProtoObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomerProtoObject defaultInstance;
    public static CustomerProtoObject getDefaultInstance() {
      return defaultInstance;
    }

    public CustomerProtoObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerProtoObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              city_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              classificationPoints_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              country_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              customerId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              customerName_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              customerType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              territory_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              valuePoint_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              classLabel_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              cisco30_ = input.readBool();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              relationship_ = input.readBool();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              differentiated_ = input.readBool();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              contractValue_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              loyaltyDuration_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              onCap_ = input.readBool();
              break;
            }
            case 130: {
              if (!((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
                valueRulesFired_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00008000;
              }
              valueRulesFired_.add(input.readBytes());
              break;
            }
            case 136: {
              if (!((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
                firedSet_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00010000;
              }
              firedSet_.add(input.readInt32());
              break;
            }
            case 138: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00010000) == 0x00010000) && input.getBytesUntilLimit() > 0) {
                firedSet_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00010000;
              }
              while (input.getBytesUntilLimit() > 0) {
                firedSet_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
          valueRulesFired_ = new com.google.protobuf.UnmodifiableLazyStringList(valueRulesFired_);
        }
        if (((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
          firedSet_ = java.util.Collections.unmodifiableList(firedSet_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neevtech.gpb.CustomerProtos.internal_static_CustomerProtoObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neevtech.gpb.CustomerProtos.internal_static_CustomerProtoObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neevtech.gpb.CustomerProtos.CustomerProtoObject.class, com.neevtech.gpb.CustomerProtos.CustomerProtoObject.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomerProtoObject> PARSER =
        new com.google.protobuf.AbstractParser<CustomerProtoObject>() {
      public CustomerProtoObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerProtoObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerProtoObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string city = 1;
    public static final int CITY_FIELD_NUMBER = 1;
    private java.lang.Object city_;
    /**
     * <code>optional string city = 1;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string city = 1;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string city = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 classificationPoints = 2;
    public static final int CLASSIFICATIONPOINTS_FIELD_NUMBER = 2;
    private int classificationPoints_;
    /**
     * <code>optional int32 classificationPoints = 2;</code>
     */
    public boolean hasClassificationPoints() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 classificationPoints = 2;</code>
     */
    public int getClassificationPoints() {
      return classificationPoints_;
    }

    // optional string country = 3;
    public static final int COUNTRY_FIELD_NUMBER = 3;
    private java.lang.Object country_;
    /**
     * <code>optional string country = 3;</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string country = 3;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          country_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string country = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string customerId = 4;
    public static final int CUSTOMERID_FIELD_NUMBER = 4;
    private java.lang.Object customerId_;
    /**
     * <code>required string customerId = 4;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string customerId = 4;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string customerId = 4;</code>
     *
     * <pre>
     * Unique ID for collaboration request.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string customerName = 5;
    public static final int CUSTOMERNAME_FIELD_NUMBER = 5;
    private java.lang.Object customerName_;
    /**
     * <code>optional string customerName = 5;</code>
     */
    public boolean hasCustomerName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string customerName = 5;</code>
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string customerName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string customerType = 6;
    public static final int CUSTOMERTYPE_FIELD_NUMBER = 6;
    private java.lang.Object customerType_;
    /**
     * <code>optional string customerType = 6;</code>
     */
    public boolean hasCustomerType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string customerType = 6;</code>
     */
    public java.lang.String getCustomerType() {
      java.lang.Object ref = customerType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string customerType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerTypeBytes() {
      java.lang.Object ref = customerType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string territory = 7;
    public static final int TERRITORY_FIELD_NUMBER = 7;
    private java.lang.Object territory_;
    /**
     * <code>optional string territory = 7;</code>
     */
    public boolean hasTerritory() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string territory = 7;</code>
     */
    public java.lang.String getTerritory() {
      java.lang.Object ref = territory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          territory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string territory = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTerritoryBytes() {
      java.lang.Object ref = territory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        territory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 valuePoint = 8;
    public static final int VALUEPOINT_FIELD_NUMBER = 8;
    private int valuePoint_;
    /**
     * <code>optional int32 valuePoint = 8;</code>
     */
    public boolean hasValuePoint() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 valuePoint = 8;</code>
     */
    public int getValuePoint() {
      return valuePoint_;
    }

    // optional string classLabel = 9 [default = "NONE"];
    public static final int CLASSLABEL_FIELD_NUMBER = 9;
    private java.lang.Object classLabel_;
    /**
     * <code>optional string classLabel = 9 [default = "NONE"];</code>
     */
    public boolean hasClassLabel() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string classLabel = 9 [default = "NONE"];</code>
     */
    public java.lang.String getClassLabel() {
      java.lang.Object ref = classLabel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          classLabel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string classLabel = 9 [default = "NONE"];</code>
     */
    public com.google.protobuf.ByteString
        getClassLabelBytes() {
      java.lang.Object ref = classLabel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bool cisco30 = 10;
    public static final int CISCO30_FIELD_NUMBER = 10;
    private boolean cisco30_;
    /**
     * <code>optional bool cisco30 = 10;</code>
     */
    public boolean hasCisco30() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional bool cisco30 = 10;</code>
     */
    public boolean getCisco30() {
      return cisco30_;
    }

    // optional bool relationship = 11;
    public static final int RELATIONSHIP_FIELD_NUMBER = 11;
    private boolean relationship_;
    /**
     * <code>optional bool relationship = 11;</code>
     */
    public boolean hasRelationship() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional bool relationship = 11;</code>
     */
    public boolean getRelationship() {
      return relationship_;
    }

    // optional bool differentiated = 12;
    public static final int DIFFERENTIATED_FIELD_NUMBER = 12;
    private boolean differentiated_;
    /**
     * <code>optional bool differentiated = 12;</code>
     */
    public boolean hasDifferentiated() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional bool differentiated = 12;</code>
     */
    public boolean getDifferentiated() {
      return differentiated_;
    }

    // optional int32 contractValue = 13;
    public static final int CONTRACTVALUE_FIELD_NUMBER = 13;
    private int contractValue_;
    /**
     * <code>optional int32 contractValue = 13;</code>
     */
    public boolean hasContractValue() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 contractValue = 13;</code>
     */
    public int getContractValue() {
      return contractValue_;
    }

    // optional int32 loyaltyDuration = 14;
    public static final int LOYALTYDURATION_FIELD_NUMBER = 14;
    private int loyaltyDuration_;
    /**
     * <code>optional int32 loyaltyDuration = 14;</code>
     */
    public boolean hasLoyaltyDuration() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 loyaltyDuration = 14;</code>
     */
    public int getLoyaltyDuration() {
      return loyaltyDuration_;
    }

    // optional bool onCap = 15;
    public static final int ONCAP_FIELD_NUMBER = 15;
    private boolean onCap_;
    /**
     * <code>optional bool onCap = 15;</code>
     */
    public boolean hasOnCap() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional bool onCap = 15;</code>
     */
    public boolean getOnCap() {
      return onCap_;
    }

    // repeated string valueRulesFired = 16;
    public static final int VALUERULESFIRED_FIELD_NUMBER = 16;
    private com.google.protobuf.LazyStringList valueRulesFired_;
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    public java.util.List<java.lang.String>
        getValueRulesFiredList() {
      return valueRulesFired_;
    }
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    public int getValueRulesFiredCount() {
      return valueRulesFired_.size();
    }
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    public java.lang.String getValueRulesFired(int index) {
      return valueRulesFired_.get(index);
    }
    /**
     * <code>repeated string valueRulesFired = 16;</code>
     */
    public com.google.protobuf.ByteString
        getValueRulesFiredBytes(int index) {
      return valueRulesFired_.getByteString(index);
    }

    // repeated int32 firedSet = 17;
    public static final int FIREDSET_FIELD_NUMBER = 17;
    private java.util.List<java.lang.Integer> firedSet_;
    /**
     * <code>repeated int32 firedSet = 17;</code>
     */
    public java.util.List<java.lang.Integer>
        getFiredSetList() {
      return firedSet_;
    }
    /**
     * <code>repeated int32 firedSet = 17;</code>
     */
    public int getFiredSetCount() {
      return firedSet_.size();
    }
    /**
     * <code>repeated int32 firedSet = 17;</code>
     */
    public int getFiredSet(int index) {
      return firedSet_.get(index);
    }

    private void initFields() {
      city_ = "";
      classificationPoints_ = 0;
      country_ = "";
      customerId_ = "";
      customerName_ = "";
      customerType_ = "";
      territory_ = "";
      valuePoint_ = 0;
      classLabel_ = "NONE";
      cisco30_ = false;
      relationship_ = false;
      differentiated_ = false;
      contractValue_ = 0;
      loyaltyDuration_ = 0;
      onCap_ = false;
      valueRulesFired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      firedSet_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCustomerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCityBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, classificationPoints_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCountryBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCustomerIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getCustomerNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCustomerTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTerritoryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, valuePoint_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getClassLabelBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBool(10, cisco30_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBool(11, relationship_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBool(12, differentiated_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, contractValue_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, loyaltyDuration_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBool(15, onCap_);
      }
      for (int i = 0; i < valueRulesFired_.size(); i++) {
        output.writeBytes(16, valueRulesFired_.getByteString(i));
      }
      for (int i = 0; i < firedSet_.size(); i++) {
        output.writeInt32(17, firedSet_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCityBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, classificationPoints_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCountryBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCustomerIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCustomerNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCustomerTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTerritoryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, valuePoint_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getClassLabelBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, cisco30_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, relationship_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, differentiated_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, contractValue_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, loyaltyDuration_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, onCap_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < valueRulesFired_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(valueRulesFired_.getByteString(i));
        }
        size += dataSize;
        size += 2 * getValueRulesFiredList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < firedSet_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(firedSet_.get(i));
        }
        size += dataSize;
        size += 2 * getFiredSetList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.neevtech.gpb.CustomerProtos.CustomerProtoObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.neevtech.gpb.CustomerProtos.CustomerProtoObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomerProtoObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.neevtech.gpb.CustomerProtos.CustomerProtoObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.neevtech.gpb.CustomerProtos.internal_static_CustomerProtoObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.neevtech.gpb.CustomerProtos.internal_static_CustomerProtoObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.neevtech.gpb.CustomerProtos.CustomerProtoObject.class, com.neevtech.gpb.CustomerProtos.CustomerProtoObject.Builder.class);
      }

      // Construct using com.neevtech.gpb.CustomerProtos.CustomerProtoObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        classificationPoints_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        country_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        customerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        customerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        customerType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        territory_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        valuePoint_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        classLabel_ = "NONE";
        bitField0_ = (bitField0_ & ~0x00000100);
        cisco30_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        relationship_ = false;
        bitField0_ = (bitField0_ & ~0x00000400);
        differentiated_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        contractValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        loyaltyDuration_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        onCap_ = false;
        bitField0_ = (bitField0_ & ~0x00004000);
        valueRulesFired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00008000);
        firedSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.neevtech.gpb.CustomerProtos.internal_static_CustomerProtoObject_descriptor;
      }

      public com.neevtech.gpb.CustomerProtos.CustomerProtoObject getDefaultInstanceForType() {
        return com.neevtech.gpb.CustomerProtos.CustomerProtoObject.getDefaultInstance();
      }

      public com.neevtech.gpb.CustomerProtos.CustomerProtoObject build() {
        com.neevtech.gpb.CustomerProtos.CustomerProtoObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.neevtech.gpb.CustomerProtos.CustomerProtoObject buildPartial() {
        com.neevtech.gpb.CustomerProtos.CustomerProtoObject result = new com.neevtech.gpb.CustomerProtos.CustomerProtoObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.classificationPoints_ = classificationPoints_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.customerId_ = customerId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.customerName_ = customerName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.customerType_ = customerType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.territory_ = territory_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.valuePoint_ = valuePoint_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.classLabel_ = classLabel_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.cisco30_ = cisco30_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.relationship_ = relationship_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.differentiated_ = differentiated_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.contractValue_ = contractValue_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.loyaltyDuration_ = loyaltyDuration_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.onCap_ = onCap_;
        if (((bitField0_ & 0x00008000) == 0x00008000)) {
          valueRulesFired_ = new com.google.protobuf.UnmodifiableLazyStringList(
              valueRulesFired_);
          bitField0_ = (bitField0_ & ~0x00008000);
        }
        result.valueRulesFired_ = valueRulesFired_;
        if (((bitField0_ & 0x00010000) == 0x00010000)) {
          firedSet_ = java.util.Collections.unmodifiableList(firedSet_);
          bitField0_ = (bitField0_ & ~0x00010000);
        }
        result.firedSet_ = firedSet_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.neevtech.gpb.CustomerProtos.CustomerProtoObject) {
          return mergeFrom((com.neevtech.gpb.CustomerProtos.CustomerProtoObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.neevtech.gpb.CustomerProtos.CustomerProtoObject other) {
        if (other == com.neevtech.gpb.CustomerProtos.CustomerProtoObject.getDefaultInstance()) return this;
        if (other.hasCity()) {
          bitField0_ |= 0x00000001;
          city_ = other.city_;
          onChanged();
        }
        if (other.hasClassificationPoints()) {
          setClassificationPoints(other.getClassificationPoints());
        }
        if (other.hasCountry()) {
          bitField0_ |= 0x00000004;
          country_ = other.country_;
          onChanged();
        }
        if (other.hasCustomerId()) {
          bitField0_ |= 0x00000008;
          customerId_ = other.customerId_;
          onChanged();
        }
        if (other.hasCustomerName()) {
          bitField0_ |= 0x00000010;
          customerName_ = other.customerName_;
          onChanged();
        }
        if (other.hasCustomerType()) {
          bitField0_ |= 0x00000020;
          customerType_ = other.customerType_;
          onChanged();
        }
        if (other.hasTerritory()) {
          bitField0_ |= 0x00000040;
          territory_ = other.territory_;
          onChanged();
        }
        if (other.hasValuePoint()) {
          setValuePoint(other.getValuePoint());
        }
        if (other.hasClassLabel()) {
          bitField0_ |= 0x00000100;
          classLabel_ = other.classLabel_;
          onChanged();
        }
        if (other.hasCisco30()) {
          setCisco30(other.getCisco30());
        }
        if (other.hasRelationship()) {
          setRelationship(other.getRelationship());
        }
        if (other.hasDifferentiated()) {
          setDifferentiated(other.getDifferentiated());
        }
        if (other.hasContractValue()) {
          setContractValue(other.getContractValue());
        }
        if (other.hasLoyaltyDuration()) {
          setLoyaltyDuration(other.getLoyaltyDuration());
        }
        if (other.hasOnCap()) {
          setOnCap(other.getOnCap());
        }
        if (!other.valueRulesFired_.isEmpty()) {
          if (valueRulesFired_.isEmpty()) {
            valueRulesFired_ = other.valueRulesFired_;
            bitField0_ = (bitField0_ & ~0x00008000);
          } else {
            ensureValueRulesFiredIsMutable();
            valueRulesFired_.addAll(other.valueRulesFired_);
          }
          onChanged();
        }
        if (!other.firedSet_.isEmpty()) {
          if (firedSet_.isEmpty()) {
            firedSet_ = other.firedSet_;
            bitField0_ = (bitField0_ & ~0x00010000);
          } else {
            ensureFiredSetIsMutable();
            firedSet_.addAll(other.firedSet_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCustomerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.neevtech.gpb.CustomerProtos.CustomerProtoObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.neevtech.gpb.CustomerProtos.CustomerProtoObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string city = 1;
      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 1;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string city = 1;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 1;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 1;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 1;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        city_ = value;
        onChanged();
        return this;
      }

      // optional int32 classificationPoints = 2;
      private int classificationPoints_ ;
      /**
       * <code>optional int32 classificationPoints = 2;</code>
       */
      public boolean hasClassificationPoints() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 classificationPoints = 2;</code>
       */
      public int getClassificationPoints() {
        return classificationPoints_;
      }
      /**
       * <code>optional int32 classificationPoints = 2;</code>
       */
      public Builder setClassificationPoints(int value) {
        bitField0_ |= 0x00000002;
        classificationPoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 classificationPoints = 2;</code>
       */
      public Builder clearClassificationPoints() {
        bitField0_ = (bitField0_ & ~0x00000002);
        classificationPoints_ = 0;
        onChanged();
        return this;
      }

      // optional string country = 3;
      private java.lang.Object country_ = "";
      /**
       * <code>optional string country = 3;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string country = 3;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 3;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 3;</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000004);
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 3;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        country_ = value;
        onChanged();
        return this;
      }

      // required string customerId = 4;
      private java.lang.Object customerId_ = "";
      /**
       * <code>required string customerId = 4;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public boolean hasCustomerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string customerId = 4;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string customerId = 4;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string customerId = 4;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string customerId = 4;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public Builder clearCustomerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>required string customerId = 4;</code>
       *
       * <pre>
       * Unique ID for collaboration request.
       * </pre>
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        customerId_ = value;
        onChanged();
        return this;
      }

      // optional string customerName = 5;
      private java.lang.Object customerName_ = "";
      /**
       * <code>optional string customerName = 5;</code>
       */
      public boolean hasCustomerName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string customerName = 5;</code>
       */
      public java.lang.String getCustomerName() {
        java.lang.Object ref = customerName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          customerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string customerName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerNameBytes() {
        java.lang.Object ref = customerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string customerName = 5;</code>
       */
      public Builder setCustomerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        customerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string customerName = 5;</code>
       */
      public Builder clearCustomerName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        customerName_ = getDefaultInstance().getCustomerName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string customerName = 5;</code>
       */
      public Builder setCustomerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        customerName_ = value;
        onChanged();
        return this;
      }

      // optional string customerType = 6;
      private java.lang.Object customerType_ = "";
      /**
       * <code>optional string customerType = 6;</code>
       */
      public boolean hasCustomerType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string customerType = 6;</code>
       */
      public java.lang.String getCustomerType() {
        java.lang.Object ref = customerType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          customerType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string customerType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerTypeBytes() {
        java.lang.Object ref = customerType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string customerType = 6;</code>
       */
      public Builder setCustomerType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        customerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string customerType = 6;</code>
       */
      public Builder clearCustomerType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        customerType_ = getDefaultInstance().getCustomerType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string customerType = 6;</code>
       */
      public Builder setCustomerTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        customerType_ = value;
        onChanged();
        return this;
      }

      // optional string territory = 7;
      private java.lang.Object territory_ = "";
      /**
       * <code>optional string territory = 7;</code>
       */
      public boolean hasTerritory() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string territory = 7;</code>
       */
      public java.lang.String getTerritory() {
        java.lang.Object ref = territory_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          territory_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string territory = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTerritoryBytes() {
        java.lang.Object ref = territory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          territory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string territory = 7;</code>
       */
      public Builder setTerritory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        territory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string territory = 7;</code>
       */
      public Builder clearTerritory() {
        bitField0_ = (bitField0_ & ~0x00000040);
        territory_ = getDefaultInstance().getTerritory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string territory = 7;</code>
       */
      public Builder setTerritoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        territory_ = value;
        onChanged();
        return this;
      }

      // optional int32 valuePoint = 8;
      private int valuePoint_ ;
      /**
       * <code>optional int32 valuePoint = 8;</code>
       */
      public boolean hasValuePoint() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 valuePoint = 8;</code>
       */
      public int getValuePoint() {
        return valuePoint_;
      }
      /**
       * <code>optional int32 valuePoint = 8;</code>
       */
      public Builder setValuePoint(int value) {
        bitField0_ |= 0x00000080;
        valuePoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 valuePoint = 8;</code>
       */
      public Builder clearValuePoint() {
        bitField0_ = (bitField0_ & ~0x00000080);
        valuePoint_ = 0;
        onChanged();
        return this;
      }

      // optional string classLabel = 9 [default = "NONE"];
      private java.lang.Object classLabel_ = "NONE";
      /**
       * <code>optional string classLabel = 9 [default = "NONE"];</code>
       */
      public boolean hasClassLabel() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string classLabel = 9 [default = "NONE"];</code>
       */
      public java.lang.String getClassLabel() {
        java.lang.Object ref = classLabel_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          classLabel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string classLabel = 9 [default = "NONE"];</code>
       */
      public com.google.protobuf.ByteString
          getClassLabelBytes() {
        java.lang.Object ref = classLabel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          classLabel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string classLabel = 9 [default = "NONE"];</code>
       */
      public Builder setClassLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        classLabel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string classLabel = 9 [default = "NONE"];</code>
       */
      public Builder clearClassLabel() {
        bitField0_ = (bitField0_ & ~0x00000100);
        classLabel_ = getDefaultInstance().getClassLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string classLabel = 9 [default = "NONE"];</code>
       */
      public Builder setClassLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        classLabel_ = value;
        onChanged();
        return this;
      }

      // optional bool cisco30 = 10;
      private boolean cisco30_ ;
      /**
       * <code>optional bool cisco30 = 10;</code>
       */
      public boolean hasCisco30() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional bool cisco30 = 10;</code>
       */
      public boolean getCisco30() {
        return cisco30_;
      }
      /**
       * <code>optional bool cisco30 = 10;</code>
       */
      public Builder setCisco30(boolean value) {
        bitField0_ |= 0x00000200;
        cisco30_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool cisco30 = 10;</code>
       */
      public Builder clearCisco30() {
        bitField0_ = (bitField0_ & ~0x00000200);
        cisco30_ = false;
        onChanged();
        return this;
      }

      // optional bool relationship = 11;
      private boolean relationship_ ;
      /**
       * <code>optional bool relationship = 11;</code>
       */
      public boolean hasRelationship() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional bool relationship = 11;</code>
       */
      public boolean getRelationship() {
        return relationship_;
      }
      /**
       * <code>optional bool relationship = 11;</code>
       */
      public Builder setRelationship(boolean value) {
        bitField0_ |= 0x00000400;
        relationship_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool relationship = 11;</code>
       */
      public Builder clearRelationship() {
        bitField0_ = (bitField0_ & ~0x00000400);
        relationship_ = false;
        onChanged();
        return this;
      }

      // optional bool differentiated = 12;
      private boolean differentiated_ ;
      /**
       * <code>optional bool differentiated = 12;</code>
       */
      public boolean hasDifferentiated() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bool differentiated = 12;</code>
       */
      public boolean getDifferentiated() {
        return differentiated_;
      }
      /**
       * <code>optional bool differentiated = 12;</code>
       */
      public Builder setDifferentiated(boolean value) {
        bitField0_ |= 0x00000800;
        differentiated_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool differentiated = 12;</code>
       */
      public Builder clearDifferentiated() {
        bitField0_ = (bitField0_ & ~0x00000800);
        differentiated_ = false;
        onChanged();
        return this;
      }

      // optional int32 contractValue = 13;
      private int contractValue_ ;
      /**
       * <code>optional int32 contractValue = 13;</code>
       */
      public boolean hasContractValue() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 contractValue = 13;</code>
       */
      public int getContractValue() {
        return contractValue_;
      }
      /**
       * <code>optional int32 contractValue = 13;</code>
       */
      public Builder setContractValue(int value) {
        bitField0_ |= 0x00001000;
        contractValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contractValue = 13;</code>
       */
      public Builder clearContractValue() {
        bitField0_ = (bitField0_ & ~0x00001000);
        contractValue_ = 0;
        onChanged();
        return this;
      }

      // optional int32 loyaltyDuration = 14;
      private int loyaltyDuration_ ;
      /**
       * <code>optional int32 loyaltyDuration = 14;</code>
       */
      public boolean hasLoyaltyDuration() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 loyaltyDuration = 14;</code>
       */
      public int getLoyaltyDuration() {
        return loyaltyDuration_;
      }
      /**
       * <code>optional int32 loyaltyDuration = 14;</code>
       */
      public Builder setLoyaltyDuration(int value) {
        bitField0_ |= 0x00002000;
        loyaltyDuration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 loyaltyDuration = 14;</code>
       */
      public Builder clearLoyaltyDuration() {
        bitField0_ = (bitField0_ & ~0x00002000);
        loyaltyDuration_ = 0;
        onChanged();
        return this;
      }

      // optional bool onCap = 15;
      private boolean onCap_ ;
      /**
       * <code>optional bool onCap = 15;</code>
       */
      public boolean hasOnCap() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional bool onCap = 15;</code>
       */
      public boolean getOnCap() {
        return onCap_;
      }
      /**
       * <code>optional bool onCap = 15;</code>
       */
      public Builder setOnCap(boolean value) {
        bitField0_ |= 0x00004000;
        onCap_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool onCap = 15;</code>
       */
      public Builder clearOnCap() {
        bitField0_ = (bitField0_ & ~0x00004000);
        onCap_ = false;
        onChanged();
        return this;
      }

      // repeated string valueRulesFired = 16;
      private com.google.protobuf.LazyStringList valueRulesFired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValueRulesFiredIsMutable() {
        if (!((bitField0_ & 0x00008000) == 0x00008000)) {
          valueRulesFired_ = new com.google.protobuf.LazyStringArrayList(valueRulesFired_);
          bitField0_ |= 0x00008000;
         }
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public java.util.List<java.lang.String>
          getValueRulesFiredList() {
        return java.util.Collections.unmodifiableList(valueRulesFired_);
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public int getValueRulesFiredCount() {
        return valueRulesFired_.size();
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public java.lang.String getValueRulesFired(int index) {
        return valueRulesFired_.get(index);
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public com.google.protobuf.ByteString
          getValueRulesFiredBytes(int index) {
        return valueRulesFired_.getByteString(index);
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public Builder setValueRulesFired(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueRulesFiredIsMutable();
        valueRulesFired_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public Builder addValueRulesFired(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueRulesFiredIsMutable();
        valueRulesFired_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public Builder addAllValueRulesFired(
          java.lang.Iterable<java.lang.String> values) {
        ensureValueRulesFiredIsMutable();
        super.addAll(values, valueRulesFired_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public Builder clearValueRulesFired() {
        valueRulesFired_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00008000);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueRulesFired = 16;</code>
       */
      public Builder addValueRulesFiredBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueRulesFiredIsMutable();
        valueRulesFired_.add(value);
        onChanged();
        return this;
      }

      // repeated int32 firedSet = 17;
      private java.util.List<java.lang.Integer> firedSet_ = java.util.Collections.emptyList();
      private void ensureFiredSetIsMutable() {
        if (!((bitField0_ & 0x00010000) == 0x00010000)) {
          firedSet_ = new java.util.ArrayList<java.lang.Integer>(firedSet_);
          bitField0_ |= 0x00010000;
         }
      }
      /**
       * <code>repeated int32 firedSet = 17;</code>
       */
      public java.util.List<java.lang.Integer>
          getFiredSetList() {
        return java.util.Collections.unmodifiableList(firedSet_);
      }
      /**
       * <code>repeated int32 firedSet = 17;</code>
       */
      public int getFiredSetCount() {
        return firedSet_.size();
      }
      /**
       * <code>repeated int32 firedSet = 17;</code>
       */
      public int getFiredSet(int index) {
        return firedSet_.get(index);
      }
      /**
       * <code>repeated int32 firedSet = 17;</code>
       */
      public Builder setFiredSet(
          int index, int value) {
        ensureFiredSetIsMutable();
        firedSet_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 firedSet = 17;</code>
       */
      public Builder addFiredSet(int value) {
        ensureFiredSetIsMutable();
        firedSet_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 firedSet = 17;</code>
       */
      public Builder addAllFiredSet(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFiredSetIsMutable();
        super.addAll(values, firedSet_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 firedSet = 17;</code>
       */
      public Builder clearFiredSet() {
        firedSet_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00010000);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CustomerProtoObject)
    }

    static {
      defaultInstance = new CustomerProtoObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CustomerProtoObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerProtoObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomerProtoObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\"\374\002\n\023CustomerProtoObject" +
      "\022\014\n\004city\030\001 \001(\t\022\034\n\024classificationPoints\030\002" +
      " \001(\005\022\017\n\007country\030\003 \001(\t\022\022\n\ncustomerId\030\004 \002(" +
      "\t\022\024\n\014customerName\030\005 \001(\t\022\024\n\014customerType\030" +
      "\006 \001(\t\022\021\n\tterritory\030\007 \001(\t\022\022\n\nvaluePoint\030\010" +
      " \001(\005\022\030\n\nclassLabel\030\t \001(\t:\004NONE\022\017\n\007cisco3" +
      "0\030\n \001(\010\022\024\n\014relationship\030\013 \001(\010\022\026\n\016differe" +
      "ntiated\030\014 \001(\010\022\025\n\rcontractValue\030\r \001(\005\022\027\n\017" +
      "loyaltyDuration\030\016 \001(\005\022\r\n\005onCap\030\017 \001(\010\022\027\n\017" +
      "valueRulesFired\030\020 \003(\t\022\020\n\010firedSet\030\021 \003(\005B",
      "\"\n\020com.neevtech.gpbB\016CustomerProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CustomerProtoObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CustomerProtoObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CustomerProtoObject_descriptor,
              new java.lang.String[] { "City", "ClassificationPoints", "Country", "CustomerId", "CustomerName", "CustomerType", "Territory", "ValuePoint", "ClassLabel", "Cisco30", "Relationship", "Differentiated", "ContractValue", "LoyaltyDuration", "OnCap", "ValueRulesFired", "FiredSet", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
